### PR TITLE
Replaced symlinks with Vagrant synced_folders.

### PR DESCRIPTION
**Pull request by thom8**
Fix for xdebug.

This requires testing before merging.

### CODE REVIEW

**Comment by thom8** [comment]
bump -- netwroking issue on test ^^

**Comment by AlexSkrypnyk** [comment]
Can we please get this merged?

**Comment by Decipher** [comment]
Nope. Still doesn't work. Put breakpoints in custom module, verified that where the breakpoints where code was being executed, verified that XDebug was working when using breakpoints elsewhere, verified that this still doesn't work.

I will look into this myself when I have a bit more free time, as the approach I have suggested has been tested and does work (IIRC):

```
The best way to do it is the same way that the Travis CI does it, which is:
- Build the stub.make file with no recursion
- Delete the profile in the build result
- Symbolically link the project root relatively (../../..) into the position of the deleted profile
- Build the profile makefile into the the project root
```

**Comment by thom8** [comment]
Not relevant

**Pull request closed without merging**
