### PR TITLE
Add Drupal code linter

### PR DESCRIPTION
**Pull request by AlexSkrypnyk**
1. Added code linter DCR https://github.com/alexdesignworks/dcr (read about how it works on the project page)
2. Configured code linter to only scan custom modules.
3. Custom ruleset allows to easily customise rules on per-project basis (in fact,  skipping of generated files from features, strongarm etc. was configured using this ruleset). It also allows to prevent false positives.
4. Added composer.json with DCR as required dependency to make local installation easier.
5. The CI build will fail if there is at least one code lint problem.
6. The CI build of this PR FAILS because there are code formatting issues in current codebase. It is expected that a new PR will be created to fix those issues OR they can be addressed in this PR (please let me know).

job__7_3_-_alexdesignworks_drupalmel_-_travis_ci_and_ibis_updates_install_-_ibis_drupal_-___www_ibis_drupal_

### CODE REVIEW

**Comment by Decipher** [comment]
@alexdesignworks I think this is an awesome addition, but I think we'll need to discuss some of the tests. While I haven't checked them all out, I'd argue atleast one already: "Hook implementations should not duplicate @param documentation".

The reason I do that is not that I believe it should be done, but is so I have a nice clean PHPStorm pass. And while I could probably configure PHPStorm not to check that, I'd prefer things to work well with the least modified settings as possible as I believe it's unreasonable to expect people who wish to contribute to change their PHPStorm settings.

**Comment by AlexSkrypnyk** [comment]
@Decipher 
There are Drupal coding standards and each project should follow it. Committed pull request rules follow Drupal coding standards. If you need to configure PHPStorm for a 'clean pass' - it is totally up to you. PHPStorm has drupal support that makes it understand what hook implementation is and to not put the parameters.

Check out my other PR where everything is fixed.

**Comment by Decipher** [comment]
Yup, fair enough. I double checked the docs and that one is valid. I don't care enough to argue the point, but I think if we're going to enforce all the standards we should probably ensure it's easy enough for people to know that is the case and how best to configure their IDE.

Please add something in the wiki that describes the changes being implemented and I'll test this PR asap.

**Comment by AlexSkrypnyk** [comment]
I will modify the wiki as soon as it merged to prevent confusion. Please check #28 as that one contains this PR and fixes.

**Comment by Decipher** [comment]
Closing this PR as it's essentially a duplicate of #28, other than proving the failing test.

**Pull request closed without merging**
